# Generated by Django 2.1 on 2018-08-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание проекта')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('_startdate', models.DateTimeField(blank=True, null=True, verbose_name='Начало проекта')),
                ('_enddate', models.DateTimeField(blank=True, null=True, verbose_name='Конец проекта')),
                ('events', models.ManyToManyField(to='core.Event')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
