# Generated by Django 2.1 on 2018-08-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180829_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('staff', 'Преподаватель'), ('admin', 'Администратор')], max_length=8, verbose_name='Тип регистрации')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Персона')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='Событие')),
            ],
        ),
        migrations.AlterField(
            model_name='eventuserregistration',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('staff', 'Преподаватель'), ('admin', 'Администратор')], max_length=8, verbose_name='Роль'),
        ),
        migrations.AlterUniqueTogether(
            name='projectuserregistration',
            unique_together={('person', 'project')},
        ),
    ]
