# Generated by Django 2.1 on 2018-09-11 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180910_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание события'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
