# Generated by Django 2.1 on 2018-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180830_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subevents',
            field=models.ManyToManyField(blank=True, to='core.Subevent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(blank=True, to='core.Event'),
        ),
    ]
