# Generated by Django 2.1 on 2018-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180911_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='json',
            field=models.TextField(blank=True, null=True, verbose_name='json'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='type',
            field=models.CharField(choices=[('h', 'html'), ('j', 'json')], default='h', max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
