# Generated by Django 2.1 on 2018-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180912_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
