# Generated by Django 2.1 on 2018-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_diagnostic_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='render',
            field=models.TextField(blank=True, null=True, verbose_name='Функция отрисовки'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание диагностики'),
        ),
    ]
