# Generated by Django 2.1 on 2018-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180914_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='published',
            field=models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации'),
        ),
    ]
