# Generated by Django 2.1 on 2018-09-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_diagnostic_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Персона проверена'),
        ),
    ]
