# Generated by Django 2.1 on 2018-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181011_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='slug',
            field=models.CharField(default='sample', max_length=16, verbose_name='Slug'),
        ),
    ]
