# Generated by Django 2.1 on 2018-10-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='event',
        ),
        migrations.AddField(
            model_name='visit',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='person',
        ),
        migrations.AddField(
            model_name='visit',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='project',
        ),
        migrations.AddField(
            model_name='visit',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
