# Generated by Django 2.1 on 2018-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181023_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.Course'),
        ),
        migrations.AlterField(
            model_name='courseuserregistration',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('staff', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=8, verbose_name='Тип регистрации'),
        ),
    ]
