# Generated by Django 2.1 on 2018-10-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181030_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='current_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Course'),
        ),
    ]
