# Generated by Django 2.1 on 2018-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_person_current_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=4096, verbose_name='Тема проектной работы')),
                ('students', models.ManyToManyField(blank=True, to='core.Person')),
            ],
            options={
                'verbose_name': 'тема проектной работы',
                'verbose_name_plural': 'темы проектных работ',
            },
        ),
    ]
