# Generated by Django 2.1 on 2018-11-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_prtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='prtheme',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
    ]
