# Generated by Django 2.1 on 2018-11-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_prtheme_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='prtheme',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prtheme_chief', to='core.Person', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='prtheme',
            name='close_register_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрытие регистрации'),
        ),
        migrations.AddField(
            model_name='prtheme',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='prtheme',
            name='max_take',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество студентов'),
        ),
    ]
